### ISSUE TITLE
Plugin ignores opt in compiler options

### ISSUE THREAD

**Issue by matejdro** [BraisGabin/detekt-compiler-rules#47]
We have this set up:

```kotlin
android {
    kotlinOptions {
        freeCompilerArgs += "-opt-in=kotlinx.coroutines.ExperimentalCoroutinesApi"
        freeCompilerArgs += "-opt-in=kotlinx.coroutines.FlowPreview"
    }
}
```

But detekt rule seems to ignore those and report `OPT_IN_USAGE` anyway.

**Comment by BraisGabin** [comment]
Yes. To fix this you should use the compiler plugin of detekt. It was released on 1.23.0. There is nothing I can do here to fix it because as a rule I can't access to that information.
